### ISSUE TITLE
To-do list for RfPy

### ISSUE THREAD

**Issue by paudetseis** [paudetseis/RfPy#7]
- [ ] Accept either StDb or obspy.inventory object (or seamlessly switch between them using StDb tools)
- [ ] Include QC thresholding using hierarchical clustering of correlation matrix
- [ ] Convert core functions (H-k, CCP) to FORTRAN to improve speed
